import { IProject, SkillsProps } from "./types";

export const skillsData:SkillsProps[] = [
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
    percentage: '100%',
    title: 'HTML',
    description: 'Mám pokročilou znalost HTML prvků a jsem zkušený v tvorbě moderních responzivních webových stránek. Rozumím fungování internetu, optimalizaci webových stránek pro SEO, hostingům a doménám. Mým cílem je vytvářet stránky, které jsou přístupné a uživatelsky přívětivé.',
    projects: '10+ dokončených projektů',
    experience: 'Zkušenost s komerčním vývojem',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
    percentage: '100%',
    title: 'CSS',
    description: 'Mám hluboké porozumění CSS a jsem zkušený v práci na stylování layoutu, animací a interakcí stránek. Mým cílem je vytvářet vizuálně atraktivní a funkční designy, které zlepšují uživatelskou zkušenost.',
    projects: '10+ dokončených projektů',
    experience: 'Zkušenost s komerčním vývojem',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
    percentage: '100%',
    title: 'Tailwind CSS',
    description: 'Jsem zkušený v používání Tailwind CSS pro stylování, což jsem využil v několika projektech v Next.js. Tento nástroj mi umožňuje rychle a efektivně vytvářet responzivní a moderní designy.',
    projects: '5+ dokončených projektů',
    experience: 'Zkušenost s vývojem osobních projektů',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    percentage: '100%',
    title: 'Javascript',
    description: 'Mám rozsáhlé zkušenosti s Javascriptem, který jsem využil při tvorbě řady webových stránek. Mým cílem je vytvářet interaktivní a funkční webové stránky, které zlepšují uživatelskou zkušenost.',
    projects: '10+ dokončených projektů',
    experience: 'Zkušenost s komerčním vývojem',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    percentage: '80%',
    title: 'Typescript',
    description: 'Typescript jsem začal používat nedávno a stále se s ním seznamuji. Využívám ho především u osobních projektů, jako jsou webové aplikace, kde mi pomáhá vytvářet robustnější a bezpečnější kód.',
    projects: '5+ dokončených projektů',
    experience: 'Zkušenost s vývojem osobních projektů',
  },
  {
    imgSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    percentage: '100%',
    title: 'React Js',
    description: 'Mám zkušenosti s tvorbou webových aplikací v Reactu. Při tvorbě jsem používal komponenty a balíčky třetích stran, a mám hluboké porozumění pro hooky, router, stav a další klíčové aspekty Reactu.',
    projects: '5+ Dokončených projektů',
    experience: 'Zkušenost s komerčním vývojem',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
    percentage: '80%',
    title: 'Next Js',
    description: 'S Next.js jsem vytvořil několik osobních projektů, kde jsem se naučil principy jako server a client components, data fetching, authorization a API endpoints. Tento nástroj mi umožňuje vytvářet vysoce výkonné webové aplikace.',
    projects: '5+ Dokončených projektů',
    experience: 'Zkušenost s vývojem osobních projektů',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-plain.svg",
    percentage: '100%',
    title: 'Wordpress',
    description: 'Přes Wordpress tvořím především webové stránky a prezentace s pomocí elementor builderu a custom kódu. Mám také zkušenost s tvorbou e-shopů přes Woocommerce, což mi umožňuje vytvářet komplexní webové řešení pro mé klienty.',
    projects: '10+ Dokončených projektů',
    experience: 'Zkušenost s komerčním vývojem',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg",
    percentage: '100%',
    title: 'Vs Code',
    description: 'Vs Code je můj preferovaný vývojový nástroj, který používám při každém svém projektu. Jsem zkušený v jeho prostředí, zejména co se týče konzole a debugování kódu.',
    projects: '',
    experience: 'Zkušenost s komerčním vývojem',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/visualstudio/visualstudio-plain.svg",
    percentage: '100%',
    title: 'Visual studio',
    description: 'Visual studio používám denně v mém zaměstnání, kde programuji nové prvky do informačních systémů. Jsem zkušený v práci s Nuget balíčky, konzolí a debugováním kódu.',
    projects: '',
    experience: 'Zkušenost s komerčním vývojem',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    percentage: '50%',
    title: 'Python',
    description: 'V Pythonu jsem zkoušel různé projekty, jako je voice chatbot, práce s daty, scrapování a podobně. Tento jazyk mi umožňuje experimentovat s různými technologiemi a rozšiřovat své dovednosti.',
    projects: '5+ Dokončených projektů',
    experience: 'Zkušenost s vývojem osobních projektů',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg",
    percentage: '100%',
    title: 'C#',
    description: 'V C# jsem pracoval v některých předmětech ve škole, kde jsme se učili například základy algoritmizace, objektově orientované programování a návrhové vzory a aplikační frameworky. Dále jej používám při práci, kde implementuji nové prvky do již existujících informačních systémů.',
    projects: '10+',
    experience: 'Zkušenost s komerčním vývojem informačních systémů',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg",
    percentage: '50%',
    title: 'C++',
    description: 'V C++ jsem si vytvořil několik konzolových projektů a také jsem měl ve škole předmět programování v C++, který byl zaměřen na OOP a práci s ukazateli. Tento jazyk mi umožňuje vytvářet efektivní a výkonný kód.',
    projects: '5+',
    experience: 'Zkušenost v oblasti základů objektového programování',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg",
    percentage: '50%',
    title: 'C',
    description: 'V jazyku C jsem na škole dokončil předměty jako základy C, algoritmy a datové struktury a embdeed systémy s mikropočítači. Tento jazyk mi umožňuje vytvářet efektivní a výkonný kód.',
    projects: '',
    experience: 'Zkušenost v oblasti základů paměti, ukazatelů, algoritmů a datových struktur',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain-wordmark.svg",
    percentage: '100%',
    title: 'MSSQL',
    description: 'MSSQL používám denně při zaměstnání, kde načítám data z MSSQL pomocí Nhiberante do našeho informačního systému. Také jsem s MSSQL pracoval při studiu v předmětech jako databázové systémy, webové aplikace nebo praktikum programování. Tato dovednost mi umožňuje efektivně manipulovat s databázovými daty a vytvářet robustní databázové řešení.',
    projects: '',
    experience: 'Zkušenost s databází MSSQL při komerčním vývoji',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    percentage: '40%',
    title: 'Mongo DB',
    description: 'Mongo DB používám u některých mých osobních projektů jako jsou webové aplikace. Tato nástroj mi umožňuje pracovat s flexibilními, dokumentovými databázemi, které se dobře hodí pro moderní webové aplikace.',
    projects: '5+',
    experience: 'Zkušenost s vývojem osobních projektů',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    percentage: '100%',
    title: 'Git',
    description: 'Git používám denně při zaměstnání u verzování projektů a také jsem jej používal při studiu. Tento nástroj mi umožňuje efektivně spravovat a sledovat změny v kódu během vývoje.',
    projects: '',
    experience: 'Zkušenost s verzováním v komerčním vývoji',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg",
    percentage: '80%',
    title: 'Adobe illustrator',
    description: 'V Adobe Illustratoru kreslím především loga nebo některé grafické prvky, které poté využívám v Canvě. Tento nástroj mi umožňuje vytvářet profesionální a atraktivní grafické prvky pro mé projekty.',
    projects: '',
    experience: 'Zkušenost s komerční tvorbou grafiky',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg",
    percentage: '50%',
    title: 'Figma',
    description: 'Figmu využívám především pro grafické návrhy mých projektů, kde navrhuji jenom layout stránek. S animacemi a interakcí ve Figma nemám zkušenosti, ale tento nástroj mi umožňuje vytvářet čisté a uživatelsky přívětivé designy.',
    projects: '',
    experience: 'Zkušenost s komerční tvorbou grafiky',
  },
  {
    imgSrc: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/canva/canva-original.svg",
    percentage: '100%',
    title: 'Canva',
    description: 'V Canvě tvořím především grafiku pro bannery, letáky nebo zde kompletuji moje předtvořené grafické návrhy s Adobe Illustrátor. Tento nástroj mi umožňuje rychle a efektivně vytvářet atraktivní vizuální obsah pro mé projekty.',
    projects: '',
    experience: 'Zkušenost s komerční tvorbou grafiky',
  },
]

export const projects: IProject[] = [
    { 
      name: "HsPro - Stavební firma",
      description:
        "Webová stránka pro stavební firmu. Stránka byla vytvořena pomocí CMS systému Wordpress. Byl vytvořen grafický návrh a zajištěn hosting s doménou. Na stránce bylo také provedeno kompletní SEO. ",
      image_path: "images/web-hspro.png",
      deployed_url: "https://hspro.cz/",
      github_url: "https://github.com/pilcikpatrik",
      category: ["Weby"],
      key_techs: ["Wordpress", "Figma", "RankMath", "Javascript", "CSS" ],
      mockups: ["images/web-hspro.png", "images/web-hspro-2.png", "images/web-hspro-3.png" ],
      dribble_url: "",
    },
    {
      name: "JP - Zednicke Práce ",
      image_path: "images/web-jp.png",
      deployed_url: "https://www.jpzednickeprace.cz/",
      github_url: "https://github.com/pilcikpatrik",
      category: ["Weby"],
      description:
        "Webová stránka pro živnostníka. Stránka byla vytvořena pomocí CMS systému Wordpress. Byl vytvořen grafický návrh a zajištěn hosting s doménou. Na stránce bylo také provedeno kompletní SEO.",
      key_techs: [ "Wordpress", "Figma", "RankMath", "Javascript", "CSS" ],
      mockups: ["images/web-jp.png", "images/web-jp-2.png", "images/web-jp-3.png" ],
      dribble_url: "",
    },
  
    {
      name: "C.I.S. - Vývoj softwaru",
      image_path: "images/web-cis.png",
      deployed_url: "https://www.cisvp.cz/",
      github_url: "https://github.com/pilcikpatrik",
      category: ["Weby"],
      description:
        "Webová stránka pro firmu C.I.S. se kterou momentálně spolupracuji. Stránka byla vytvořena pomocí React JS.",
      key_techs: [
        "React",
        "html",
        "CSS",
        "Javascript"
      ],
      mockups: ["images/web-cis.png", "images/web-cis-2.png", "images/web-cis-3.png" ],
      dribble_url: "",
    },
  
    {
      name: "Logo - JPZednictvi",
      image_path: "images/jp-logo.svg",
      deployed_url: "https://www.jpzednickeprace.cz/",
      github_url: "",
      category: ["Loga"],
      description:
        "Tvorba loga pro zedníka na živnosti. Základ byl vytvořen v Adobe Illustrator a zbytek detailu byl dodělán pomocí Canvy.",
      key_techs: ["Adobe illustrator", "Canva"],
      mockups: ["images/jp-logo.svg", "images/jp-logo-cap.png", "images/jp-logo-cup.png"  ],
      dribble_url: "https://dribbble.com/pilcikpatrik",
    },
  
    {
      name: "Logo - Tesařství A&K",
      image_path: "images/ak-logo.svg",
      deployed_url: "",
      github_url: "",
      category: ["Loga"],
      description:
        "Tvorba loga pro tesařskou firmu. Základ byl vytvořen v Adobe Illustrator a zbytek detailu byl dodělán pomocí Canvy. ",
      key_techs: ["Adobe illustrator", "Canva"],
      mockups: [ "images/ak-logo.svg", "images/logo-v1-cap.png", "images/logo-v1-cup.png" ],
      dribble_url: "https://dribbble.com/pilcikpatrik",
    },
  
    {
      name: "Logo - Krowka.cz",
      image_path: "images/krowka-logo.svg",
      deployed_url: "https://www.krowka.cz/",
      github_url: "",
      category: ["Loga"],
      description:
        "Tvorba loga pro Eshop Krowka.cz. Celé logo bylo vytvořeno pomocí Adobe Illustrator.",
      key_techs: ["Adobe illustrator"],
      mockups: [ "images/krowka-logo.svg", "images/logo-v2-mockup-cap.png", "images/logo-v2-mockup-cup.png" ],
      dribble_url: "https://dribbble.com/pilcikpatrik",
    },
    {
      name: "Grafika - HSPro",
      image_path: "images/hspro-letak.svg",
      deployed_url: "https://hspro.cz/",
      github_url: "",
      category: ["Tiskoviny"],
      description:
        'Kompletní grafické práce pro firmu HSPro. Tyto práce zahrnovali tvorbu Letáku, brožury a banneru na cestu.',
      key_techs: ["Adobe illustrator", "Canva"],
      mockups: ["images/hspro-letak.svg", "images/hspro-brozura.svg", "images/hspro-banner.svg" ],
      dribble_url: "https://dribbble.com/pilcikpatrik",
    },
    {
      name: "Grafika - Krowka.cz",
      image_path: "images/krowka-brozura.svg",
      deployed_url: "https://www.krowka.cz/",
      github_url: "",
      category: ["Tiskoviny"],
      description:
        "Grafické práce a dlouhodobá spolupráce s Eshopem Krowka.cz. Tvorba bannerů, letáků, brožur, grafiky pro reklamu a eventy.",
      key_techs: ["Adobe illustrator", "Canva"],
      mockups: ["images/krowka-brozura.svg", "images/krowka-letak.svg", "images/krowka-showcase.svg" ],
      dribble_url: "https://dribbble.com/pilcikpatrik",
    },
    {
      name: "Grafika - Tesařství A&K",
      image_path: "images/ak-letak.svg",
      deployed_url: "",
      github_url: "",
      category: ["Tiskoviny"],
      description:
        'Kompletní grafické práce pro firmu Tesařství A&K. Tyto práce zahrnovali tvorbu Letáků, brožur a vizitek.',
      key_techs: ["Adobe illustrator", "Canva"],
      mockups: ["images/ak-letak.svg", "images/ak-letak-zed.svg", "images/ak-vizitka.svg" ],
      dribble_url: "https://dribbble.com/pilcikpatrik",
    },
  ];
